-- Supabase PostgreSQL Table Setup
-- Run this SQL in your Supabase SQL Editor to create the 'todos' table.

CREATE TABLE IF NOT EXISTS todos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task text NOT NULL,
  completed boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optional: If Row Level Security (RLS) is enabled on your Supabase project,
-- you can enable it and add policies to allow anonymous/public read and write operations
-- since this is a simple learning application.
-- Alternatively, you can disable RLS for this specific table for local development testing:
--
-- ALTER TABLE todos DISABLE ROW LEVEL SECURITY;
